version: "3"
services:
  httpd:
    build:
      context: .
      dockerfile: ./Dockerfile.httpd
    ports:
      - "80"
    environment:
      - PORT=80
  lighttpd:
    build:
      context: .
      dockerfile: ./Dockerfile.lighttpd
    ports:
      - "80"
    environment:
      - PORT=80
  